"""Small mag in field name

Revision ID: 983ab7df046d
Revises: 7809c69f7311
Create Date: 2025-11-03 05:35:55.383776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '983ab7df046d'
down_revision: Union[str, Sequence[str], None] = '7809c69f7311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_memberships', sa.Column('is_member', sa.Boolean(), nullable=False))
    op.drop_column('event_memberships', 'is_memeber')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_memberships', sa.Column('is_memeber', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('event_memberships', 'is_member')
    # ### end Alembic commands ###
