"""Dating profiles and additional user model added

Revision ID: e97da6ccd8a3
Revises: ba5b9f2bd6d1
Create Date: 2025-11-13 14:18:59.161461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97da6ccd8a3'
down_revision: Union[str, Sequence[str], None] = 'ba5b9f2bd6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=100), server_default='Не указано', nullable=False),
    sa.Column('alias', sa.String(length=100), server_default='Анонимный пользователь', nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('birthday', sa.DateTime(), nullable=False),
    sa.Column('interests', sa.String(length=150), nullable=False),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex', create_type=False), nullable=True),
    sa.Column('social_link', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dating_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('photo', sa.String(length=300), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('interests', sa.String(length=300), nullable=False),
    sa.Column('goal', sa.String(length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('member_events', sa.Column('info_message_id', sa.BigInteger(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('profile_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'users', 'user_profiles', ['profile_id'], ['id'])
    op.drop_column('users', 'alias')
    op.drop_column('users', 'rating')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("'Не указано'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('alias', sa.VARCHAR(length=100), server_default=sa.text("'Анонимный пользователь'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    op.drop_column('member_events', 'info_message_id')
    op.drop_table('dating_profiles')
    op.drop_table('user_profiles')
    op.execute('DROP TYPE IF EXISTS sex')
    # ### end Alembic commands ###
